#!/usr/bin/env python3
"""Print the CHANGELOG.md section body for one version.

Used twice: by scripts/release.sh for the annotated tag message, and by the release
workflow to feed softprops/action-gh-release with real notes instead of an
autogenerated commit list.

    python3 scripts/changelog-section.py 0.1.0
    python3 scripts/changelog-section.py v0.1.0 --file CHANGELOG.md

Exits 1 with a message on stderr if the section does not exist, so a release
workflow fails loudly rather than publishing empty notes.
"""

import argparse
import re
import sys


def extract(text: str, version: str) -> str:
    version = version.lstrip("v")
    # Headings look like "## [0.1.0] - 2026-09-05" or "## [Unreleased]". Match the
    # bracketed version exactly so 0.1.0 never matches 0.1.10.
    pattern = re.compile(
        r"^##\s+\[" + re.escape(version) + r"\](?:[^\n]*)\n(.*?)(?=^##\s+\[|\Z)",
        re.S | re.M,
    )
    match = pattern.search(text)
    if not match:
        raise SystemExit(f"changelog-section: no section for [{version}]")
    return match.group(1).strip()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("version")
    parser.add_argument("--file", default="CHANGELOG.md")
    args = parser.parse_args()

    try:
        text = open(args.file, encoding="utf-8").read()
    except OSError as exc:
        raise SystemExit(f"changelog-section: {exc}")

    body = extract(text, args.version)
    if not body:
        raise SystemExit(f"changelog-section: section [{args.version}] is empty")
    print(body)
    return 0


if __name__ == "__main__":
    sys.exit(main())
